"""Delivery of mechanical test data into the materials data set of 70-71C.

Anchor: ECSS-Q-ST-70-45 interface clause (mechanical property data generated by
the test methods is delivered into the ECSS-Q-ST-70-71C materials data set).
Paraphrased into an implementable procedure; no standard text is reproduced.

Procedure implemented here
--------------------------
1. Validate one delivery entry against the mandatory metadata the data set
   keys on: material designation, product form, heat, condition, orientation,
   property, value with its unit and the temperature it was measured at.
2. Normalise the entry into the data set's own units -- stress in MPa,
   temperature in kelvin, strain as a dimensionless ratio -- so entries from
   laboratories reporting in ksi, Fahrenheit or percent land on one scale.
3. Build the data set key from the fields that make two entries comparable.
   Temperature enters the key through a bucket, because two measurements a
   fraction of a degree apart describe the same condition and must not split
   into two populations.
4. Group the accepted entries by that key, reject the rest with a reason
   each, and report a group carrying fewer entries than the data set needs
   as present but not yet usable as a design value.
"""

import math

__all__ = [
    "STRESS_FACTORS_TO_MPA",
    "STRAIN_FACTORS",
    "TEMPERATURE_UNITS",
    "REQUIRED_FIELDS",
    "PROPERTY_KINDS",
    "ORIENTATIONS",
    "TEMPERATURE_BUCKET_K",
    "MIN_ENTRIES_PER_GROUP",
    "stress_units",
    "convert_stress_to_mpa",
    "convert_temperature_to_kelvin",
    "convert_strain",
    "temperature_bucket",
    "normalise_entry",
    "dataset_key",
    "build_dataset",
]

# Stress units a laboratory may report in, expressed in MPa.
STRESS_FACTORS_TO_MPA = {
    "mpa": 1.0,
    "n/mm2": 1.0,
    "gpa": 1000.0,
    "ksi": 6.894757293168361,
    "psi": 0.006894757293168361,
}

# Strain units, expressed as a dimensionless ratio.
STRAIN_FACTORS = {
    "-": 1.0,
    "mm/mm": 1.0,
    "%": 0.01,
    "percent": 0.01,
}

TEMPERATURE_UNITS = ("k", "c", "degc", "f", "degf")

# Metadata the data set keys on; an entry short of any of them is not
# deliverable, because nobody downstream can say what it describes.
REQUIRED_FIELDS = (
    "material_designation",
    "product_form",
    "heat",
    "condition",
    "orientation",
    "property",
    "value",
    "unit",
    "temperature",
    "temperature_unit",
)

# Properties the data set carries, with the quantity kind each one is.
PROPERTY_KINDS = {
    "yield_strength": "stress",
    "tensile_strength": "stress",
    "compressive_yield_strength": "stress",
    "shear_strength": "stress",
    "bearing_strength": "stress",
    "elastic_modulus": "stress",
    "elongation": "strain",
    "reduction_of_area": "strain",
}

ORIENTATIONS = ("l", "lt", "st", "45", "unspecified")

# Two measurements inside one bucket describe the same thermal condition.
TEMPERATURE_BUCKET_K = 5.0

# A group with fewer entries than this is present in the data set but is not
# yet a population anything can be derived from.
MIN_ENTRIES_PER_GROUP = 3

_ABSOLUTE_ZERO_C = -273.15


def stress_units():
    """Return the sorted stress units the delivery accepts."""
    return sorted(STRESS_FACTORS_TO_MPA)


def _clean_token(value, label):
    """Return a non-empty lowercase token, raising on anything else."""
    if not isinstance(value, str):
        raise ValueError("%s must be a string, got %r" % (label, value))
    token = value.strip().lower()
    if not token:
        raise ValueError("%s must not be blank" % label)
    return token


def _finite(value, label):
    """Return a finite float, raising on anything else."""
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        raise ValueError("%s must be a real number, got %r" % (label, value))
    number = float(value)
    if not math.isfinite(number):
        raise ValueError("%s must be finite" % label)
    return number


def convert_stress_to_mpa(value, unit):
    """Return a stress expressed in MPa."""
    token = _clean_token(unit, "unit")
    if token not in STRESS_FACTORS_TO_MPA:
        raise ValueError(
            "unknown stress unit %r; accepted units are %s"
            % (unit, ", ".join(stress_units()))
        )
    number = _finite(value, "value")
    if number <= 0.0:
        raise ValueError("a stress delivered to the data set must be positive, got %g" % number)
    return number * STRESS_FACTORS_TO_MPA[token]


def convert_strain(value, unit):
    """Return a strain expressed as a dimensionless ratio."""
    token = _clean_token(unit, "unit")
    if token not in STRAIN_FACTORS:
        raise ValueError(
            "unknown strain unit %r; accepted units are %s"
            % (unit, ", ".join(sorted(STRAIN_FACTORS)))
        )
    number = _finite(value, "value")
    if number < 0.0:
        raise ValueError("a strain delivered to the data set must not be negative")
    return number * STRAIN_FACTORS[token]


def convert_temperature_to_kelvin(value, unit):
    """Return a test temperature expressed in kelvin."""
    token = _clean_token(unit, "temperature_unit")
    if token not in TEMPERATURE_UNITS:
        raise ValueError(
            "unknown temperature unit %r; accepted units are %s"
            % (unit, ", ".join(TEMPERATURE_UNITS))
        )
    number = _finite(value, "temperature")
    if token == "k":
        kelvin = number
    elif token in ("c", "degc"):
        kelvin = number - _ABSOLUTE_ZERO_C
    else:
        kelvin = (number - 32.0) * 5.0 / 9.0 - _ABSOLUTE_ZERO_C
    if kelvin <= 0.0:
        raise ValueError("a test temperature at or below absolute zero is not physical")
    return kelvin


def temperature_bucket(kelvin, width=TEMPERATURE_BUCKET_K):
    """Return the integer bucket index a test temperature falls in."""
    number = _finite(kelvin, "kelvin")
    if number <= 0.0:
        raise ValueError("kelvin must be positive, got %g" % number)
    size = _finite(width, "width")
    if size <= 0.0:
        raise ValueError("width must be positive, got %g" % size)
    return int(math.floor(number / size + 0.5))


def normalise_entry(entry):
    """Return one delivery entry converted into the data set's own units."""
    if not isinstance(entry, dict):
        raise ValueError("entry must be a mapping")
    for field in REQUIRED_FIELDS:
        if field not in entry:
            raise ValueError("entry missing mandatory field '%s'" % field)
    prop = _clean_token(entry["property"], "property")
    if prop not in PROPERTY_KINDS:
        raise ValueError(
            "unknown property %r; the data set carries %s"
            % (entry["property"], ", ".join(sorted(PROPERTY_KINDS)))
        )
    orientation = _clean_token(entry["orientation"], "orientation")
    if orientation not in ORIENTATIONS:
        raise ValueError(
            "unknown orientation %r; accepted orientations are %s"
            % (entry["orientation"], ", ".join(ORIENTATIONS))
        )
    kind = PROPERTY_KINDS[prop]
    if kind == "stress":
        value = convert_stress_to_mpa(entry["value"], entry["unit"])
        unit = "mpa"
    else:
        value = convert_strain(entry["value"], entry["unit"])
        unit = "-"
    kelvin = convert_temperature_to_kelvin(entry["temperature"], entry["temperature_unit"])
    return {
        "material_designation": _clean_token(
            entry["material_designation"], "material_designation"
        ),
        "product_form": _clean_token(entry["product_form"], "product_form"),
        "heat": _clean_token(entry["heat"], "heat"),
        "condition": _clean_token(entry["condition"], "condition"),
        "orientation": orientation,
        "property": prop,
        "kind": kind,
        "value": value,
        "unit": unit,
        "temperature_k": kelvin,
        "temperature_bucket": temperature_bucket(kelvin),
    }


def dataset_key(normalised):
    """Return the data set key two comparable entries share."""
    if not isinstance(normalised, dict):
        raise ValueError("normalised must be a mapping produced by normalise_entry")
    for field in ("material_designation", "product_form", "condition",
                  "orientation", "property", "temperature_bucket"):
        if field not in normalised:
            raise ValueError("normalised entry missing '%s'" % field)
    return (
        normalised["material_designation"],
        normalised["product_form"],
        normalised["condition"],
        normalised["orientation"],
        normalised["property"],
        normalised["temperature_bucket"],
    )


def build_dataset(entries, min_entries=MIN_ENTRIES_PER_GROUP):
    """Group a batch of delivery entries into the data set, rejecting the rest."""
    if not isinstance(entries, (list, tuple)):
        raise ValueError("entries must be a sequence of delivery entries")
    if not isinstance(min_entries, int) or isinstance(min_entries, bool):
        raise ValueError("min_entries must be an integer")
    if min_entries < 1:
        raise ValueError("min_entries must be at least 1, got %d" % min_entries)
    groups = {}
    order = []
    rejected = []
    accepted = []
    for index, entry in enumerate(entries):
        try:
            normalised = normalise_entry(entry)
        except ValueError as error:
            rejected.append({"index": index, "reason": str(error)})
            continue
        accepted.append(normalised)
        key = dataset_key(normalised)
        if key not in groups:
            groups[key] = []
            order.append(key)
        groups[key].append(normalised)
    summary = []
    findings = []
    for key in order:
        members = groups[key]
        heats = sorted({member["heat"] for member in members})
        total = 0.0
        for member in members:
            total += member["value"]
        record = {
            "key": key,
            "entries": len(members),
            "heats": heats,
            "mean_value": total / len(members),
            "usable": len(members) >= min_entries,
        }
        summary.append(record)
        if not record["usable"]:
            findings.append(
                "group %s carries %d entries against the %d a usable population needs"
                % ("/".join(str(part) for part in key), len(members), min_entries)
            )
    for item in rejected:
        findings.append("entry %d is not deliverable: %s" % (item["index"], item["reason"]))
    return {
        "accepted": accepted,
        "rejected": rejected,
        "groups": summary,
        "group_count": len(summary),
        "findings": findings,
        "deliverable": bool(summary) and not findings,
    }
