#!/usr/bin/env python3
"""Generate packages/aero-agent-skills/manifest.json from the tree at HEAD.

The npm package (CLI + MCP server) must never hand-carry metadata: this
script derives every entry the same way the gated tooling does —
frontmatter via yaml.safe_load exactly as scripts/router_eval.py reads it,
counts copied from docs/metrics.json (itself generated by gen_visuals.py),
standards from standards-map.yaml. The JS router then scores manifest
name/description/tags plus the SKILL.md body on disk, so its inputs are
byte-identical to gate 5's.

Usage: gen_manifest.py [--check]
  --check  regenerate in memory and fail (exit 1) if the committed
           manifest differs — wired into `make visuals-check`.
"""

import json
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "packages" / "aero-agent-skills" / "manifest.json"


def load_skills():
    skills = []
    for p in sorted((ROOT / "skills").rglob("SKILL.md")):
        text = p.read_text(encoding="utf-8")
        if not text.startswith("---"):
            continue
        parts = text.split("---", 2)
        try:
            fm = yaml.safe_load(parts[1])
        except Exception:  # noqa: BLE001
            fm = None
        if not isinstance(fm, dict):
            continue
        rel = p.parent.relative_to(ROOT / "skills")
        meta = fm.get("metadata")
        if not isinstance(meta, dict):
            meta = {}
        seg = rel.parts
        skills.append({
            "path": str(rel),
            "name": fm.get("name", "") or "",
            "description": fm.get("description", "") or "",
            "tags": [str(t).lower() for t in (meta.get("tags") or [])],
            "family": seg[0],
            "pack": seg[1] if len(seg) >= 3 else None,
            "router_doc": len(seg) == 1,
        })
    return skills


def load_standards():
    doc = yaml.safe_load((ROOT / "standards-map.yaml").read_text(encoding="utf-8"))
    out = []
    for s in doc.get("standards", []):
        out.append({
            "id": s.get("id", ""),
            "name": s.get("name", ""),
            "publisher": s.get("publisher", ""),
            "status": s.get("status", ""),
            "domain": s.get("domain", ""),
            "gated": bool(s.get("gated", False)),
        })
    return out


def build():
    metrics = json.loads((ROOT / "docs" / "metrics.json").read_text(encoding="utf-8"))
    manifest = {
        "schema": "aero-agent-skills/manifest@1",
        "counts": {
            "leaves": metrics["leaves"],
            "live_packs": metrics["live_packs"],
            "families": metrics["families"],
            "corpus_tasks": metrics["corpus_tasks"],
        },
        "skills": load_skills(),
        "standards": load_standards(),
    }
    return json.dumps(manifest, indent=1, ensure_ascii=False) + "\n"


def main():
    text = build()
    if "--check" in sys.argv[1:]:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("FAIL manifest-check: %s is stale — run `make visuals`" % OUT.relative_to(ROOT), file=sys.stderr)
            sys.exit(1)
        print("PASS manifest-check: %s regenerates to zero diff" % OUT.relative_to(ROOT))
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print("wrote %s (%d skills, %d standards)" % (
        OUT.relative_to(ROOT), text.count('"path":'), text.count('"publisher":')))


if __name__ == "__main__":
    main()
