#!/usr/bin/env python3
"""ECSS-E-ST-32C clause 4.6.2.21 micro-vibration analysis
(paraphrase, not copy).

Common-knowledge summary: clause 4.6.2.21 addresses the analysis of
low-level vibration disturbances induced on a spacecraft by rotating
equipment (reaction wheels, momentum wheels, cryocoolers, pumps),
periodic-low-frequency actuators (solar array drives), and impulsive
devices (thruster valves). Rotating sources generate harmonics at
integer multiples of the spin frequency. Structural transmissibility
governs how much source amplitude reaches sensitive equipment; for a
second-order passive isolation system transmissibility is unity below
the isolation natural frequency and rolls off as (f_isolation/f)^2
above it. Compliance is checked by comparing the peak in-band induced
amplitude against the instrument micro-vibration allowable. This module
implements source categorization, harmonic frequency computation,
transmissibility, frequency-band overlap checking, induced amplitude
computation, and per-instrument compliance assessment. Impulsive sources
are flagged for broadband review; the harmonic framework does not clear
them.
"""

ROTATING_SOURCE_TYPES = frozenset(
    {"reaction_wheel", "momentum_wheel", "cryocooler", "pump"}
)
PERIODIC_LOW_FREQ_SOURCE_TYPES = frozenset({"solar_array_drive"})
IMPULSIVE_SOURCE_TYPES = frozenset({"thruster_valve"})

# Harmonic orders generated by each rotating source type.
# Orders are integer multiples of spin frequency.
ROTATING_HARMONIC_ORDERS = {
    "reaction_wheel": (1, 2, 3, 4, 6, 8),
    "momentum_wheel": (1, 2, 4, 6),
    "cryocooler": (1, 2, 3),
    "pump": (1, 2, 4),
}

SOURCE_CATEGORY_ROTATING = "rotating"
SOURCE_CATEGORY_PERIODIC = "periodic_low_frequency"
SOURCE_CATEGORY_IMPULSIVE = "impulsive"

NO_IN_BAND_HARMONIC = "no_in_band_harmonic"


def categorize_source(source_type):
    """Return the disturbance-mechanism category for a source type:
    'rotating', 'periodic_low_frequency', or 'impulsive'.
    Raises ValueError for an unrecognized source type."""
    if source_type in ROTATING_SOURCE_TYPES:
        return SOURCE_CATEGORY_ROTATING
    if source_type in PERIODIC_LOW_FREQ_SOURCE_TYPES:
        return SOURCE_CATEGORY_PERIODIC
    if source_type in IMPULSIVE_SOURCE_TYPES:
        return SOURCE_CATEGORY_IMPULSIVE
    raise ValueError(
        "unrecognized disturbance source type %r under "
        "E-ST-32C clause 4.6.2.21" % (source_type,)
    )


def compute_harmonic_frequencies(source_type, spin_freq_hz):
    """Return the list of harmonic frequencies (Hz) for a rotating or
    periodic-low-frequency source at the given fundamental frequency.

    For rotating source types the harmonics are the integer-multiple
    orders defined in ROTATING_HARMONIC_ORDERS.  For
    periodic-low-frequency types the harmonic list is [spin_freq_hz]
    (the drive frequency is the fundamental).  Impulsive sources carry
    no harmonic series; raises ValueError if called for one.

    Raises ValueError for non-positive spin_freq_hz or an impulsive
    or unrecognized source type."""
    if spin_freq_hz <= 0.0:
        raise ValueError("spin_freq_hz must be positive, got %r" % (spin_freq_hz,))
    category = categorize_source(source_type)
    if category == SOURCE_CATEGORY_IMPULSIVE:
        raise ValueError(
            "impulsive source type %r has no harmonic series; "
            "use a broadband assessment" % (source_type,)
        )
    if category == SOURCE_CATEGORY_ROTATING:
        orders = ROTATING_HARMONIC_ORDERS[source_type]
        return [round(spin_freq_hz * order, 6) for order in orders]
    # periodic_low_frequency: fundamental only
    return [round(spin_freq_hz, 6)]


def compute_transmissibility(freq_hz, isolation_freq_hz):
    """Structural transmissibility T(f) for a second-order passive
    isolation system with natural frequency isolation_freq_hz.

    T = 1.0 for freq_hz <= isolation_freq_hz (rigid-body region).
    T = (isolation_freq_hz / freq_hz)^2 for freq_hz > isolation_freq_hz
    (isolation roll-off region, simplified single-breakpoint model).

    Raises ValueError for non-positive arguments."""
    if freq_hz <= 0.0:
        raise ValueError("freq_hz must be positive, got %r" % (freq_hz,))
    if isolation_freq_hz <= 0.0:
        raise ValueError(
            "isolation_freq_hz must be positive, got %r" % (isolation_freq_hz,)
        )
    if freq_hz <= isolation_freq_hz:
        return 1.0
    ratio = isolation_freq_hz / freq_hz
    return ratio * ratio


def check_frequency_band_overlap(harmonic_freqs_hz, band_low_hz, band_high_hz):
    """Return the subset of harmonic_freqs_hz that fall within the
    closed interval [band_low_hz, band_high_hz].

    Raises ValueError when band_low_hz >= band_high_hz."""
    if band_low_hz >= band_high_hz:
        raise ValueError(
            "sensitive band must have band_low_hz < band_high_hz, "
            "got (%r, %r)" % (band_low_hz, band_high_hz)
        )
    return [f for f in harmonic_freqs_hz if band_low_hz <= f <= band_high_hz]


def compute_induced_amplitude(source_amplitude, transmissibility):
    """Amplitude at the instrument after structural transfer:
    source_amplitude * transmissibility.

    Raises ValueError for negative source_amplitude or transmissibility."""
    if source_amplitude < 0.0:
        raise ValueError(
            "source_amplitude must be >= 0, got %r" % (source_amplitude,)
        )
    if transmissibility < 0.0:
        raise ValueError(
            "transmissibility must be >= 0, got %r" % (transmissibility,)
        )
    return source_amplitude * transmissibility


def assess_source_at_instrument(
    source_type,
    spin_freq_hz,
    source_amplitude,
    isolation_freq_hz,
    instrument_band_hz,
    instrument_allowable,
):
    """Full harmonic-path micro-vibration assessment for one disturbance
    source against one sensitive instrument.

    instrument_band_hz: (band_low_hz, band_high_hz) tuple.
    instrument_allowable: numeric allowable amplitude, or None if the
    requirement has not been established (itself a finding).

    Returns a dict:
      category             -- source disturbance-mechanism category
      harmonic_freqs_hz    -- list of source harmonic frequencies
      in_band_freqs        -- harmonics within the instrument band
      worst_transmissibility -- highest T(f) among in-band harmonics
      worst_induced_amplitude -- peak induced amplitude at instrument
      exceeds_allowable    -- True when induced > allowable
      missing_allowable    -- True when allowable is None and in-band
                              harmonics exist
      compliant            -- True only when no exceedance and no
                              missing_allowable finding
      finding              -- short string label

    Raises ValueError for an impulsive source (no harmonic series),
    unrecognized source type, or invalid band."""
    band_low_hz, band_high_hz = instrument_band_hz
    category = categorize_source(source_type)

    if category == SOURCE_CATEGORY_IMPULSIVE:
        raise ValueError(
            "impulsive source %r requires broadband assessment; "
            "harmonic compliance check does not apply" % (source_type,)
        )

    harmonic_freqs = compute_harmonic_frequencies(source_type, spin_freq_hz)
    in_band = check_frequency_band_overlap(harmonic_freqs, band_low_hz, band_high_hz)

    if not in_band:
        return {
            "category": category,
            "harmonic_freqs_hz": harmonic_freqs,
            "in_band_freqs": [],
            "worst_transmissibility": 0.0,
            "worst_induced_amplitude": 0.0,
            "exceeds_allowable": False,
            "missing_allowable": False,
            "compliant": True,
            "finding": NO_IN_BAND_HARMONIC,
        }

    transmissibilities = [
        compute_transmissibility(f, isolation_freq_hz) for f in in_band
    ]
    worst_t = max(transmissibilities)
    worst_amp = compute_induced_amplitude(source_amplitude, worst_t)

    missing_allowable = instrument_allowable is None
    exceeds = (not missing_allowable) and (worst_amp > instrument_allowable)
    compliant = not exceeds and not missing_allowable

    if missing_allowable:
        finding = "missing_instrument_allowable"
    elif exceeds:
        finding = "exceedance"
    else:
        finding = "within_allowable"

    return {
        "category": category,
        "harmonic_freqs_hz": harmonic_freqs,
        "in_band_freqs": in_band,
        "worst_transmissibility": worst_t,
        "worst_induced_amplitude": round(worst_amp, 9),
        "exceeds_allowable": exceeds,
        "missing_allowable": missing_allowable,
        "compliant": compliant,
        "finding": finding,
    }


def aggregate_instrument_findings(instrument_id, assessments):
    """Aggregate a list of per-source assessment dicts for one instrument.

    Returns:
      instrument_id          -- passed through
      total_sources_assessed -- len(assessments)
      non_compliant_findings -- list of non-compliant assessment dicts
      overall_compliant      -- True only when all assessments are compliant
    """
    non_compliant = [a for a in assessments if not a.get("compliant", True)]
    return {
        "instrument_id": instrument_id,
        "total_sources_assessed": len(assessments),
        "non_compliant_findings": non_compliant,
        "overall_compliant": len(non_compliant) == 0,
    }
