#!/usr/bin/env python3
"""Solid rocket motor ballistics logic (paraphrase, deterministic, stdlib only).

Common-knowledge summary (standards-map.yaml: ecss reference-only; solid
propellant ballistics is standard engineering methodology, summary-only
here): a solid propellant grain burns normal to its exposed surface at a
rate r that follows the Vieille (St. Robert) law r = a * p^n, where a is
the burn rate coefficient and n the pressure exponent. The chamber
pressure settles where the mass generated by the burning surface equals
the choked mass flow through the throat, which gives the equilibrium
chamber pressure p_c = (rho_p * a * A_b * c* / A_t)^(1/(1-n)). The
characteristic velocity c* = sqrt(R * T_c / (gamma * (2/(gamma+1))^
((gamma+1)/(gamma-1)))) links chamber conditions to choked discharge.
Thrust follows from the specific impulse as F = Isp * g0 * m_dot, and
total impulse is F times the burn time or Isp * g0 times the propellant
mass. Grain geometry sets the burn area and the web thickness; a burn
area that grows, holds, or shrinks as the web burns is categorized as
progressive, neutral, or regressive respectively.

All units are SI: pressure Pa, rate m/s, areas m^2, mass flow kg/s,
temperature K, specific gas constant J/(kg*K), thrust N, impulse N*s,
specific impulse s, gravity m/s^2.
"""

import math

G0 = 9.80665  # standard gravity, m/s^2


def _check_positive(value, name):
    if value <= 0.0:
        raise ValueError("%s must be positive: %r" % (name, value))


def burn_rate(pressure, a, n):
    """Vieille/St. Robert burn rate r = a * p^n, in m/s.

    pressure in Pa, a in m/s per Pa^n, n dimensionless in (0, 1).
    Raises ValueError on a non-positive pressure or coefficient, or an
    exponent outside (0, 1).
    """
    _check_positive(pressure, "pressure")
    _check_positive(a, "burn rate coefficient a")
    if not (0.0 < n < 1.0):
        raise ValueError("pressure exponent n must be in (0, 1): %r" % (n,))
    return a * pressure ** n


def characteristic_velocity(T_c, gamma, R):
    """Characteristic velocity c* in m/s from chamber temperature T_c (K),
    ratio of specific heats gamma (> 1), and specific gas constant
    R (J/(kg*K)):

        c* = sqrt(R * T_c / (gamma * (2/(gamma+1))**((gamma+1)/(gamma-1))))

    Raises ValueError on non-positive inputs or gamma <= 1.
    """
    _check_positive(T_c, "chamber temperature T_c")
    _check_positive(R, "specific gas constant R")
    if gamma <= 1.0:
        raise ValueError("ratio of specific heats gamma must be > 1: %r" % (gamma,))
    return math.sqrt(
        R * T_c
        / (gamma * (2.0 / (gamma + 1.0)) ** ((gamma + 1.0) / (gamma - 1.0)))
    )


def equilibrium_chamber_pressure(rho_p, a, n, A_b, A_t, c_star):
    """Equilibrium chamber pressure p_c in Pa:

        p_c = (rho_p * a * A_b * c_star / A_t) ** (1 / (1 - n))

    where rho_p is the propellant density (kg/m^3), a the burn rate
    coefficient, n the pressure exponent in (0, 1), A_b the burn area
    (m^2), A_t the throat area (m^2), c_star the characteristic velocity
    (m/s). The n = 1 limiting case has a singular exponent: no finite
    equilibrium pressure exists, and ValueError is raised. Non-positive
    burn area or throat area also raise ValueError.
    """
    _check_positive(rho_p, "propellant density rho_p")
    _check_positive(a, "burn rate coefficient a")
    if not (0.0 < n < 1.0):
        raise ValueError(
            "pressure exponent n must be in (0, 1); n = 1 is the singular "
            "limiting case with no finite equilibrium: %r" % (n,)
        )
    _check_positive(A_b, "burn area A_b")
    _check_positive(A_t, "throat area A_t")
    _check_positive(c_star, "characteristic velocity c_star")
    return (rho_p * a * A_b * c_star / A_t) ** (1.0 / (1.0 - n))


def mass_flow(p_c, A_t, c_star):
    """Choked mass flow through the throat, m_dot = p_c * A_t / c_star (kg/s).

    Raises ValueError on non-positive inputs.
    """
    _check_positive(p_c, "chamber pressure p_c")
    _check_positive(A_t, "throat area A_t")
    _check_positive(c_star, "characteristic velocity c_star")
    return p_c * A_t / c_star


def burn_mass_flow(rho_p, A_b, rate):
    """Mass generated by the burning surface, m_dot = rho_p * A_b * r (kg/s).

    At equilibrium this equals the choked mass flow through the throat.
    Raises ValueError on non-positive inputs.
    """
    _check_positive(rho_p, "propellant density rho_p")
    _check_positive(A_b, "burn area A_b")
    _check_positive(rate, "burn rate r")
    return rho_p * A_b * rate


def thrust_from_isp(Isp, m_dot, g0=G0):
    """Thrust from specific impulse, F = Isp * g0 * m_dot (N).

    Raises ValueError on non-positive inputs.
    """
    _check_positive(Isp, "specific impulse Isp")
    _check_positive(m_dot, "mass flow m_dot")
    _check_positive(g0, "gravity g0")
    return Isp * g0 * m_dot


def total_impulse(F, burn_time):
    """Total impulse from a constant thrust and burn time, I_t = F * t_b (N*s).

    Raises ValueError on non-positive inputs.
    """
    _check_positive(F, "thrust F")
    _check_positive(burn_time, "burn time t_b")
    return F * burn_time


def total_impulse_from_propellant(Isp, m_prop, g0=G0):
    """Total impulse from specific impulse and propellant mass,
    I_t = Isp * g0 * m_prop (N*s). Raises ValueError on non-positive inputs.
    """
    _check_positive(Isp, "specific impulse Isp")
    _check_positive(m_prop, "propellant mass m_prop")
    _check_positive(g0, "gravity g0")
    return Isp * g0 * m_prop


def tubular_grain_burn_area(D_inner, L):
    """Inner-bore burn area of a tubular (cylindrical) grain,
    A_b = pi * D_inner * L (m^2), ignoring the end faces.

    Raises ValueError on non-positive inputs.
    """
    _check_positive(D_inner, "inner bore diameter D_inner")
    _check_positive(L, "grain length L")
    return math.pi * D_inner * L


def web_burn_time(web, rate):
    """Burn time for a web thickness at a given burn rate, t_b = web / r (s).

    Raises ValueError on non-positive inputs.
    """
    _check_positive(web, "web thickness web")
    _check_positive(rate, "burn rate r")
    return web / rate


def burn_area_verdict(initial_area, final_area):
    """Burn progression verdict for a grain geometry.

    'progressive' when the burn area grows as the web burns,
    'neutral' when it holds (within a 1e-9 relative tolerance),
    'regressive' when it shrinks. Raises ValueError on non-positive areas.
    """
    _check_positive(initial_area, "initial burn area")
    _check_positive(final_area, "final burn area")
    if abs(final_area - initial_area) <= 1e-9 * initial_area:
        return "neutral"
    return "progressive" if final_area > initial_area else "regressive"
