#!/usr/bin/env python3
"""Who may switch off retrigger on a limiter feeding an essential load.

Anchor: ECSS-E-ST-20-20C clause 5.2.6.4.1. The procedure below is a
paraphrase into implementable steps; no standard text is reproduced.

Disabling retrigger turns a limiter that recovers by itself into one
that stays open after the first trip. On a limiter feeding an essential
spacecraft load that is a decision to give up the load, and the clause
reserves it to commands that originate on the ground. Nothing on board
may take it.

Four things follow, and each is a way an architecture ends up with an
authority nobody intended to grant.

Origin is not the same as the moment of execution. A time-tagged
sequence uplinked from the ground and run hours later is still a ground
originated command: a person decided it and the decision is on record.
An action generated by onboard fault management is not, however sound
its reasoning, because no one on the ground decided this load would be
given up. Sorting the command paths by where they are executed rather
than where they originate is the mistake that admits autonomy through
the back door.

Essentiality is a declared property with a rationale behind it, not an
adjective. A load asserted essential with no rationale reference cannot
be assessed at all, because the strength of the protection now depends
on a word nobody can audit.

The exposure is counted, not just detected. Knowing that some essential
limiter can be disabled from onboard is less useful than knowing how
many, and which onboard path reaches the most of them: one autonomy
function with authority over a dozen essential limiters is a very
different architecture from a dozen functions with one each.

Non-essential loads are outside this clause. Recording them keeps the
denominators honest and stops the assessment quietly widening into a
rule the standard does not state.

The policy numbers below are declared project values, not physical
constants: a project substitutes its own.

Standard library only, offline, deterministic.
"""

from __future__ import annotations

import math

ESSENTIALITY_NOT_ESTABLISHED = "load-essentiality-not-established"
NON_GROUND_DISABLE_AUTHORITY = "non-ground-retrigger-disable-authority-on-essential-load"
DISABLE_AUTHORITY_GROUND_ONLY = "essential-load-retrigger-disable-authority-ground-only"

DEFAULT_AUTHORITY_POLICY = {
    "require_essentiality_rationale": True,
    "max_exposed_essential_limiters": 0,
    "blast_radius_advisory_count": 3,
}

_REL_TOL = 1e-9
_ABS_TOL = 1e-15


def _is_finite_number(value):
    return (
        isinstance(value, (int, float))
        and not isinstance(value, bool)
        and math.isfinite(value)
    )


def _require_count(name, value):
    if not isinstance(value, int) or isinstance(value, bool):
        raise ValueError("%s must be a whole number, got %r" % (name, value))
    if value < 0:
        raise ValueError("%s must not be negative, got %r" % (name, value))
    return value


def _require_flag(name, value):
    if not isinstance(value, bool):
        raise ValueError("%s must be true or false, got %r" % (name, value))
    return value


def _require_label(name, value):
    if not isinstance(value, str):
        raise ValueError("%s must be a string, got %r" % (name, value))
    return value.strip()


def _require_labels(name, value):
    if not isinstance(value, (list, tuple)):
        raise ValueError("%s must be a sequence of names, got %r" % (name, value))
    names = []
    for item in value:
        label = _require_label("%s entry" % name, item)
        if not label:
            raise ValueError("%s must not contain a blank name" % name)
        if label in names:
            raise ValueError("%s repeats %r" % (name, label))
        names.append(label)
    return tuple(names)


def _at_most(value, limit):
    """value <= limit, absorbing floating-point representation error."""
    return value <= limit or math.isclose(
        value, limit, rel_tol=_REL_TOL, abs_tol=_ABS_TOL
    )


def validate_authority_policy(policy):
    """Check the declared command-authority policy can be assessed against."""
    if not isinstance(policy, dict):
        raise ValueError("policy must be a mapping, got %r" % (policy,))
    _require_flag(
        "require_essentiality_rationale",
        policy.get("require_essentiality_rationale"),
    )
    _require_count(
        "max_exposed_essential_limiters",
        policy.get("max_exposed_essential_limiters"),
    )
    advisory = _require_count(
        "blast_radius_advisory_count", policy.get("blast_radius_advisory_count")
    )
    if advisory < 1:
        raise ValueError(
            "blast_radius_advisory_count must be at least one; an advisory "
            "that fires on zero essential limiters says nothing"
        )
    return policy


def validate_command_source(source):
    """Read one command path and where the command that uses it originates."""
    if not isinstance(source, dict):
        raise ValueError("source must be a mapping, got %r" % (source,))
    name = _require_label("command source name", source.get("name"))
    if not name:
        raise ValueError("command source name must not be blank")
    ground_originated = _require_flag(
        "ground_originated on %s" % name, source.get("ground_originated")
    )
    executed_onboard = _require_flag(
        "executed_onboard on %s" % name, source.get("executed_onboard")
    )
    return {
        "name": name,
        "ground_originated": ground_originated,
        "executed_onboard": executed_onboard,
    }


def command_source_index(sources):
    """Index every declared command path by name."""
    if not isinstance(sources, (list, tuple)) or not sources:
        raise ValueError(
            "command sources must be a non-empty sequence; authority cannot be "
            "assessed against paths nobody listed"
        )
    index = {}
    for source in sources:
        record = validate_command_source(source)
        if record["name"] in index:
            raise ValueError("duplicate command source %r" % record["name"])
        index[record["name"]] = record
    return index


def validate_limiter_record(limiter):
    """Read one limiter, the load behind it and who may disable its retrigger."""
    if not isinstance(limiter, dict):
        raise ValueError("limiter must be a mapping, got %r" % (limiter,))
    identifier = _require_label("limiter id", limiter.get("id"))
    if not identifier:
        raise ValueError("limiter id must not be blank")
    load = _require_label("load id on %s" % identifier, limiter.get("load_id"))
    if not load:
        raise ValueError("load id on %s must not be blank" % identifier)
    essential = _require_flag(
        "essential on %s" % identifier, limiter.get("essential")
    )
    rationale = _require_label(
        "essentiality_rationale on %s" % identifier,
        limiter.get("essentiality_rationale", ""),
    )
    authority = _require_labels(
        "disable_authority on %s" % identifier, limiter.get("disable_authority", ())
    )
    return {
        "id": identifier,
        "load_id": load,
        "essential": essential,
        "essentiality_rationale": rationale,
        "disable_authority": authority,
    }


def limiter_records(limiters):
    """Read every limiter on the table, in record order."""
    if not isinstance(limiters, (list, tuple)):
        raise ValueError("limiters must be a sequence of limiter records")
    if not limiters:
        raise ValueError("no limiter is on the table, so there is nothing to assess")
    records = []
    seen = set()
    for limiter in limiters:
        record = validate_limiter_record(limiter)
        if record["id"] in seen:
            raise ValueError("duplicate limiter id %r in the record" % record["id"])
        seen.add(record["id"])
        records.append(record)
    return tuple(records)


def group_by_essentiality(records):
    """Split the limiters into the essential group and the rest.

    Non-essential limiters are outside this clause; they are grouped so
    the counts below have an honest denominator, not so they are judged.
    """
    essential = tuple(record for record in records if record["essential"])
    other = tuple(record for record in records if not record["essential"])
    return essential, other


def unsupported_essentiality(records, policy=DEFAULT_AUTHORITY_POLICY):
    """Limiters asserted essential with no rationale anyone can look up."""
    validate_authority_policy(policy)
    if not policy["require_essentiality_rationale"]:
        return ()
    return tuple(
        record["id"]
        for record in records
        if record["essential"] and not record["essentiality_rationale"]
    )


def non_ground_authorities(limiter, index):
    """Paths able to disable this limiter's retrigger that do not start on ground.

    A path executed onboard is not by itself a finding: an uplinked
    time-tagged sequence runs onboard and still originates on the ground.
    """
    record = validate_limiter_record(limiter)
    offending = []
    for name in record["disable_authority"]:
        source = index.get(name)
        if source is None:
            raise ValueError(
                "limiter %s grants disable authority to %r, which is not a "
                "declared command path" % (record["id"], name)
            )
        if not source["ground_originated"]:
            offending.append(name)
    return tuple(offending)


def essential_exposure(records, index):
    """Every essential limiter whose retrigger an onboard decision could disable."""
    essential, _ = group_by_essentiality(records)
    exposure = []
    for record in essential:
        offending = non_ground_authorities(record, index)
        if offending:
            exposure.append((record["id"], offending))
    return tuple(exposure)


def exposed_essential_fraction(records, index):
    """Share of the essential limiters carrying a non-ground disable authority."""
    essential, _ = group_by_essentiality(records)
    if not essential:
        raise ValueError(
            "no limiter on the table feeds an essential load, so this clause "
            "has no population to measure"
        )
    return len(essential_exposure(records, index)) / len(essential)


def blast_radius(records, index):
    """How many essential limiters each non-ground path could disable.

    One autonomy function holding authority over a dozen essential
    limiters is a different architecture from a dozen holding one each,
    and the verdict alone does not separate them.
    """
    counts = {}
    for limiter_id, offending in essential_exposure(records, index):
        for name in offending:
            counts[name] = counts.get(name, 0) + 1
    return counts


def widest_non_ground_path(records, index):
    """The non-ground path reaching the most essential limiters, or None."""
    counts = blast_radius(records, index)
    if not counts:
        return None
    return max(sorted(counts.items()), key=lambda item: item[1])


def authority_advisories(records, index, policy=DEFAULT_AUTHORITY_POLICY):
    """Things worth saying about an architecture that already meets the clause."""
    validate_authority_policy(policy)
    advisories = []
    essential, other = group_by_essentiality(records)
    for record in essential:
        if len(record["disable_authority"]) == 0:
            advisories.append(
                "limiter %s feeding essential load %s grants retrigger-disable "
                "authority to nobody at all; ground has no way to give the "
                "load up deliberately" % (record["id"], record["load_id"])
            )
    onboard_ground_paths = sorted(
        {
            name
            for record in essential
            for name in record["disable_authority"]
            if index[name]["ground_originated"] and index[name]["executed_onboard"]
        }
    )
    if onboard_ground_paths:
        advisories.append(
            "essential-load disable authority runs through %s, which executes "
            "onboard while originating on ground; the uplink record is what "
            "makes it admissible and has to be retained"
            % ", ".join(onboard_ground_paths)
        )
    if not other:
        advisories.append(
            "every limiter on the table is marked essential; a population with "
            "no non-essential limiter usually means the marking was applied by "
            "default rather than decided"
        )
    return tuple(advisories)


def assess_essential_load_retrigger_disabling(case, policy=DEFAULT_AUTHORITY_POLICY):
    """Full clause 5.2.6.4.1 verdict for one limiter population."""
    if not isinstance(case, dict):
        raise ValueError("case must be a mapping, got %r" % (case,))
    validate_authority_policy(policy)

    findings = []
    advisories = []
    result = {
        "essential_limiters": (),
        "non_essential_limiters": (),
        "unsupported_essentiality": (),
        "exposed_limiters": (),
        "exposed_essential_count": None,
        "exposed_essential_fraction": None,
        "widest_non_ground_path": None,
        "widest_non_ground_reach": None,
        "findings": findings,
        "advisories": advisories,
    }

    index = command_source_index(case.get("command_sources"))
    records = limiter_records(case.get("limiters"))
    essential, other = group_by_essentiality(records)
    result["essential_limiters"] = tuple(record["id"] for record in essential)
    result["non_essential_limiters"] = tuple(record["id"] for record in other)

    unsupported = unsupported_essentiality(records, policy)
    result["unsupported_essentiality"] = unsupported
    if unsupported:
        for limiter_id in unsupported:
            findings.append(
                "limiter %s is asserted essential with no rationale reference, "
                "so the protection this clause gives it rests on a word nobody "
                "can audit" % limiter_id
            )
        result["verdict"] = ESSENTIALITY_NOT_ESTABLISHED
        return result

    if not essential:
        findings.append(
            "no limiter on the table feeds an essential load, so the clause "
            "has not been shown to apply to this population"
        )
        result["verdict"] = ESSENTIALITY_NOT_ESTABLISHED
        return result

    exposure = essential_exposure(records, index)
    result["exposed_limiters"] = exposure
    result["exposed_essential_count"] = len(exposure)
    result["exposed_essential_fraction"] = exposed_essential_fraction(records, index)
    widest = widest_non_ground_path(records, index)
    if widest is not None:
        result["widest_non_ground_path"] = widest[0]
        result["widest_non_ground_reach"] = widest[1]

    advisories.extend(authority_advisories(records, index, policy))

    if not _at_most(
        len(exposure), int(policy["max_exposed_essential_limiters"])
    ):
        for limiter_id, offending in exposure:
            findings.append(
                "limiter %s feeds an essential load and its retrigger can be "
                "disabled by %s, which no ground operator originates"
                % (limiter_id, ", ".join(offending))
            )
        if (
            result["widest_non_ground_reach"] is not None
            and result["widest_non_ground_reach"]
            >= int(policy["blast_radius_advisory_count"])
        ):
            findings.append(
                "the single path %s can disable retrigger on %d essential "
                "limiters; that is one decision away from giving up several "
                "essential loads at once"
                % (
                    result["widest_non_ground_path"],
                    result["widest_non_ground_reach"],
                )
            )
        result["verdict"] = NON_GROUND_DISABLE_AUTHORITY
        return result

    result["verdict"] = DISABLE_AUTHORITY_GROUND_ONLY
    return result
