"""Fatigue testing of metallic materials and reduction of an S-N data set.

Anchor: ECSS-Q-ST-70-45, methods clause -- fatigue data is generated by
cycling specimens of a declared form at a controlled frequency until failure
or until a declared run-out, and the surviving points are reduced to a stress
versus life relation. Paraphrased into an implementable procedure; no
standard text is reproduced.

What this module decides
------------------------
Which points of an S-N set may enter the fit, what relation they support, and
what the run-outs are allowed to say.

1. A run-out is censored, not a data point. The specimen did not fail, so its
   life is a lower bound; putting it in a least-squares fit pulls the curve
   towards a life nobody observed.
2. A run-out still has to be consistent. One that stopped before the fitted
   curve predicts failure constrains nothing, and reporting it as evidence of
   an endurance limit is the error this check exists for.
3. The declared run-out threshold is a contract. A point marked as run-out
   below it was stopped early, and a failure recorded beyond it contradicts
   the threshold that was declared.
4. Frequency and specimen form travel with the data. The same alloy gives a
   different curve notched, and a set run outside the frequency band is not
   comparable with one inside it.
"""

import math

__all__ = [
    "SPECIMEN_TYPES",
    "FREQUENCY_BAND_HZ",
    "MIN_FIT_POINTS",
    "validate_sn_points",
    "fit_basquin",
    "life_at_stress",
    "stress_at_life",
    "runout_findings",
    "frequency_findings",
    "specimen_findings",
    "assess_fatigue_test",
]

# Specimen forms this reduction recognises.
SPECIMEN_TYPES = (
    "unnotched-axial",
    "notched-axial",
    "rotating-bending",
    "flat-sheet",
)

# Cycling frequency band inside which the data is comparable.
FREQUENCY_BAND_HZ = (1.0, 100.0)

# A line through two points is not a fit.
MIN_FIT_POINTS = 3

# Comparisons at a limit are inclusive; absorb representation error there.
REL_TOLERANCE = 1e-9


def _as_finite_float(value, label):
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        raise ValueError("%s must be a real number, got %r" % (label, value))
    number = float(value)
    if not math.isfinite(number):
        raise ValueError("%s must be finite, got %r" % (label, value))
    return number


def _as_positive_float(value, label):
    number = _as_finite_float(value, label)
    if number <= 0.0:
        raise ValueError("%s must be positive, got %r" % (label, value))
    return number


def _slack(reference):
    return REL_TOLERANCE * max(abs(reference), 1.0)


def validate_sn_points(points):
    """Return the S-N set as validated records carrying their run-out marking."""
    if not isinstance(points, (list, tuple)) or not points:
        raise ValueError("an S-N set needs at least one point")
    records = []
    for i, item in enumerate(points):
        if not isinstance(item, dict):
            raise ValueError("point %d must be a mapping" % i)
        for key in ("stress_amplitude_mpa", "cycles"):
            if key not in item:
                raise ValueError("point %d is missing '%s'" % (i, key))
        runout = item.get("runout", False)
        if not isinstance(runout, bool):
            raise ValueError("point %d 'runout' must be a boolean" % i)
        cycles = _as_positive_float(item["cycles"], "point %d cycles" % i)
        if cycles < 1.0:
            raise ValueError("point %d records fewer than one cycle" % i)
        records.append(
            {
                "stress_amplitude_mpa": _as_positive_float(
                    item["stress_amplitude_mpa"], "point %d stress_amplitude_mpa" % i
                ),
                "cycles": cycles,
                "runout": runout,
                "index": i,
            }
        )
    return records


def fit_basquin(points):
    """Return the log-log stress-life fit taken over the failures only.

    The relation is log10(N) = intercept + exponent * log10(S). Run-outs are
    censored and take no part in the fit.
    """
    records = validate_sn_points(points)
    failures = [r for r in records if not r["runout"]]
    if len(failures) < MIN_FIT_POINTS:
        raise ValueError(
            "the set holds %d failures, at least %d are needed to fit"
            % (len(failures), MIN_FIT_POINTS)
        )
    xs = [math.log10(r["stress_amplitude_mpa"]) for r in failures]
    ys = [math.log10(r["cycles"]) for r in failures]
    n = float(len(xs))
    mean_x = sum(xs) / n
    mean_y = sum(ys) / n
    sxx = 0.0
    sxy = 0.0
    for x, y in zip(xs, ys):
        sxx += (x - mean_x) * (x - mean_x)
        sxy += (x - mean_x) * (y - mean_y)
    if sxx <= 0.0:
        raise ValueError(
            "every failure sits at the same stress amplitude; the set spans no "
            "stress range to fit against"
        )
    exponent = sxy / sxx
    intercept = mean_y - exponent * mean_x
    syy = 0.0
    residual = 0.0
    for x, y in zip(xs, ys):
        syy += (y - mean_y) * (y - mean_y)
        gap = y - (intercept + exponent * x)
        residual += gap * gap
    quality = 1.0 if syy <= 0.0 else 1.0 - residual / syy
    if exponent >= 0.0:
        raise ValueError(
            "the fit rises with stress amplitude; the set is not a fatigue "
            "curve"
        )
    return {
        "intercept": intercept,
        "exponent": exponent,
        "fit_quality": quality,
        "failures_used": len(failures),
        "runouts_censored": len(records) - len(failures),
    }


def life_at_stress(fit, stress_amplitude_mpa):
    """Return the life the fitted curve predicts at a stress amplitude."""
    if not isinstance(fit, dict) or "intercept" not in fit or "exponent" not in fit:
        raise ValueError("fit must carry 'intercept' and 'exponent'")
    stress = _as_positive_float(stress_amplitude_mpa, "stress_amplitude_mpa")
    intercept = _as_finite_float(fit["intercept"], "intercept")
    exponent = _as_finite_float(fit["exponent"], "exponent")
    return 10.0 ** (intercept + exponent * math.log10(stress))


def stress_at_life(fit, cycles):
    """Return the stress amplitude the fitted curve places at a given life."""
    if not isinstance(fit, dict) or "intercept" not in fit or "exponent" not in fit:
        raise ValueError("fit must carry 'intercept' and 'exponent'")
    life = _as_positive_float(cycles, "cycles")
    intercept = _as_finite_float(fit["intercept"], "intercept")
    exponent = _as_finite_float(fit["exponent"], "exponent")
    if exponent == 0.0:
        raise ValueError("a flat fit cannot be inverted onto a stress")
    return 10.0 ** ((math.log10(life) - intercept) / exponent)


def runout_findings(points, fit, runout_cycles):
    """Return findings about the run-outs of a set against its own threshold."""
    records = validate_sn_points(points)
    threshold = _as_positive_float(runout_cycles, "runout_cycles")
    findings = []
    for record in records:
        if record["runout"]:
            if record["cycles"] < threshold - _slack(threshold):
                findings.append(
                    "point %d is marked run-out at %.4g cycles, below the "
                    "declared threshold of %.4g"
                    % (record["index"], record["cycles"], threshold)
                )
                continue
            predicted = life_at_stress(fit, record["stress_amplitude_mpa"])
            if record["cycles"] < predicted - _slack(predicted):
                findings.append(
                    "run-out %d stopped at %.4g cycles while the fitted curve "
                    "places failure at %.4g; it constrains nothing"
                    % (record["index"], record["cycles"], predicted)
                )
        elif record["cycles"] > threshold + _slack(threshold):
            findings.append(
                "point %d records a failure at %.4g cycles, beyond the declared "
                "run-out threshold of %.4g"
                % (record["index"], record["cycles"], threshold)
            )
    return findings


def frequency_findings(frequency_hz, band=FREQUENCY_BAND_HZ):
    """Return findings for a set cycled outside the comparable frequency band."""
    frequency = _as_positive_float(frequency_hz, "frequency_hz")
    if not isinstance(band, (list, tuple)) or len(band) != 2:
        raise ValueError("band must be a (low, high) pair")
    low = _as_positive_float(band[0], "band low")
    high = _as_positive_float(band[1], "band high")
    if low >= high:
        raise ValueError("band low %g must be below high %g" % (low, high))
    if frequency < low - _slack(low) or frequency > high + _slack(high):
        return [
            "cycling frequency %.4g Hz is outside the %.4g to %.4g Hz band the "
            "data is comparable over" % (frequency, low, high)
        ]
    return []


def specimen_findings(specimen_type, stress_concentration_kt=None):
    """Return findings about the declared specimen form and its notch factor."""
    if specimen_type not in SPECIMEN_TYPES:
        raise ValueError("'%s' is not a recognised specimen form" % (specimen_type,))
    findings = []
    if specimen_type == "notched-axial":
        if stress_concentration_kt is None:
            findings.append(
                "a notched set carries no stress concentration factor; the "
                "curve cannot be applied to another notch"
            )
        else:
            kt = _as_positive_float(
                stress_concentration_kt, "stress_concentration_kt"
            )
            if kt < 1.0 - REL_TOLERANCE:
                findings.append(
                    "stress concentration factor %.4g is below unity, which no "
                    "notch produces" % kt
                )
    elif stress_concentration_kt is not None:
        findings.append(
            "specimen form '%s' is unnotched but a stress concentration factor "
            "was declared" % specimen_type
        )
    return findings


def assess_fatigue_test(spec):
    """Reduce one S-N set and report what its points and conditions support.

    spec keys: points, specimen_type, frequency_hz, runout_cycles; optional
    stress_concentration_kt and design_stress_mpa for a predicted life.
    """
    if not isinstance(spec, dict):
        raise ValueError("spec must be a mapping")
    for key in ("points", "specimen_type", "frequency_hz", "runout_cycles"):
        if key not in spec:
            raise ValueError("spec missing required key '%s'" % key)
    fit = fit_basquin(spec["points"])
    findings = []
    findings.extend(
        specimen_findings(spec["specimen_type"], spec.get("stress_concentration_kt"))
    )
    findings.extend(frequency_findings(spec["frequency_hz"]))
    findings.extend(runout_findings(spec["points"], fit, spec["runout_cycles"]))

    predicted = None
    if spec.get("design_stress_mpa") is not None:
        predicted = life_at_stress(fit, spec["design_stress_mpa"])

    return {
        "intercept": fit["intercept"],
        "exponent": fit["exponent"],
        "fit_quality": fit["fit_quality"],
        "failures_used": fit["failures_used"],
        "runouts_censored": fit["runouts_censored"],
        "stress_at_runout_life": stress_at_life(fit, spec["runout_cycles"]),
        "predicted_life_cycles": predicted,
        "findings": findings,
        "curve_usable": not findings,
    }
